"""пересоздаем таблицу

Revision ID: 12de4d08eb1d
Revises: 997b0c34c0b1
Create Date: 2026-04-29 09:17:44.610602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12de4d08eb1d'
down_revision: Union[str, Sequence[str], None] = '997b0c34c0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Привязка к пользователю'),
    sa.Column('token_id', sa.UUID(), nullable=False, comment='привязка к токену кабинета'),
    sa.Column('nm_id', sa.Integer(), nullable=False, comment='Артикул WB'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Наименование товара'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Создано'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Обновлено'),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_product_nm_id'), 'wb_product', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_product_token_id'), 'wb_product', ['token_id'], unique=False)
    op.create_index(op.f('ix_wb_product_user_id'), 'wb_product', ['user_id'], unique=False)
    op.drop_index(op.f('idx_wb_product_nm_uuid'), table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_nm_id'), table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_subject_id'), table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_subject_name'), table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_user_id'), table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_vendor_code'), table_name='wb_product_cards')
    op.drop_index(op.f('uq_wb_product_user_nmid'), table_name='wb_product_cards')
    op.drop_table('wb_product_cards')
    op.alter_column('api_tokens', 'user_id',
               existing_type=sa.UUID(),
               comment='Привязка к пользователю',
               existing_nullable=False)
    op.alter_column('api_tokens', 'marketplace',
               existing_type=postgresql.ENUM('WILDBERRIES', 'OZON', 'YANDEX_MARKET', name='marketplace_enum'),
               comment='Маркетплейс',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tokens', 'marketplace',
               existing_type=postgresql.ENUM('WILDBERRIES', 'OZON', 'YANDEX_MARKET', name='marketplace_enum'),
               comment=None,
               existing_comment='Маркетплейс',
               existing_nullable=False)
    op.alter_column('api_tokens', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Привязка к пользователю',
               existing_nullable=False)
    op.create_table('wb_product_cards',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nm_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vendor_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('photos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('characteristics', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wb_product_cards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wb_product_cards_pkey'))
    )
    op.create_index(op.f('uq_wb_product_user_nmid'), 'wb_product_cards', ['user_id', 'nm_id'], unique=True)
    op.create_index(op.f('ix_wb_product_cards_vendor_code'), 'wb_product_cards', ['vendor_code'], unique=False)
    op.create_index(op.f('ix_wb_product_cards_user_id'), 'wb_product_cards', ['user_id'], unique=False)
    op.create_index(op.f('ix_wb_product_cards_subject_name'), 'wb_product_cards', ['subject_name'], unique=False)
    op.create_index(op.f('ix_wb_product_cards_subject_id'), 'wb_product_cards', ['subject_id'], unique=False)
    op.create_index(op.f('ix_wb_product_cards_nm_id'), 'wb_product_cards', ['nm_id'], unique=False)
    op.create_index(op.f('idx_wb_product_nm_uuid'), 'wb_product_cards', ['nm_uuid'], unique=False)
    op.drop_index(op.f('ix_wb_product_user_id'), table_name='wb_product')
    op.drop_index(op.f('ix_wb_product_token_id'), table_name='wb_product')
    op.drop_index(op.f('ix_wb_product_nm_id'), table_name='wb_product')
    op.drop_table('wb_product')
    # ### end Alembic commands ###
