"""дополнительный флаг для тарифного плана

Revision ID: 133e43685280
Revises: 78563780553d
Create Date: 2026-04-16 16:42:43.670778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133e43685280'
down_revision: Union[str, Sequence[str], None] = '78563780553d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Уникальный идентификатор подписки',
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Владелец подписки',
               existing_nullable=False)
    op.alter_column('subscriptions', 'tariff_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Текущий тариф',
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Статус: 'active', 'expired', 'cancelled', 'demo'",
               existing_nullable=False)
    op.add_column('tariff_plans', sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Доступен ли тариф для выбора пользователями'))
    op.alter_column('tariff_plans', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Уникальный идентификатор',
               existing_nullable=False)
    op.alter_column('tariff_plans', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Описание для лендинга: "7 дней бесплатно, без карты"')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tariff_plans', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Описание для лендинга: "7 дней бесплатно, без карты"')
    op.alter_column('tariff_plans', 'id',
               existing_type=sa.UUID(),
               comment='Уникальный идентификатор',
               existing_nullable=False)
    op.drop_column('tariff_plans', 'is_public')
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment="Статус: 'active', 'expired', 'cancelled', 'demo'",
               existing_nullable=False)
    op.alter_column('subscriptions', 'tariff_id',
               existing_type=sa.UUID(),
               comment='Текущий тариф',
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.UUID(),
               comment='Владелец подписки',
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.UUID(),
               comment='Уникальный идентификатор подписки',
               existing_nullable=False)
    # ### end Alembic commands ###
