"""удалил свойство

Revision ID: 2f92c5b859dc
Revises: db78d6fee9e1
Create Date: 2026-04-23 10:46:35.286572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f92c5b859dc'
down_revision: Union[str, Sequence[str], None] = 'db78d6fee9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sync_states_token_id'), table_name='user_sync_states')
    op.drop_constraint(op.f('uq_sync_state'), 'user_sync_states', type_='unique')
    op.create_unique_constraint('uq_sync_state', 'user_sync_states', ['user_id', 'entity'])
    op.drop_constraint(op.f('user_sync_states_token_id_fkey'), 'user_sync_states', type_='foreignkey')
    op.drop_column('user_sync_states', 'token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sync_states', sa.Column('token_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_sync_states_token_id_fkey'), 'user_sync_states', 'api_tokens', ['token_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_sync_state', 'user_sync_states', type_='unique')
    op.create_unique_constraint(op.f('uq_sync_state'), 'user_sync_states', ['user_id', 'token_id', 'entity'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_sync_states_token_id'), 'user_sync_states', ['token_id'], unique=False)
    # ### end Alembic commands ###
