"""add token table

Revision ID: 358272a0d6c2
Revises: 9104a9446775
Create Date: 2026-02-18 10:04:38.652706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358272a0d6c2'
down_revision: Union[str, Sequence[str], None] = '9104a9446775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('marketplace', sa.Enum('WILDBERRIES', 'OZON', 'YANDEX_MARKET', name='marketplace_enum'), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_marketplace'), 'api_tokens', ['marketplace'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_type'), 'api_tokens', ['token_type'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_type'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_marketplace'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
