"""остатки по складам упрощение

Revision ID: 35a99a7be8fa
Revises: 186022a8f435
Create Date: 2026-04-28 11:21:03.275941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35a99a7be8fa'
down_revision: Union[str, Sequence[str], None] = '186022a8f435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sync_states', 'user_id',
               existing_type=sa.UUID(),
               comment='кому принадлежит состояние',
               existing_nullable=False)
    op.alter_column('user_sync_states', 'entity',
               existing_type=sa.VARCHAR(length=50),
               comment='тип данных, которые ты синкаешь',
               existing_nullable=False)
    op.alter_column('user_sync_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='когда создали запись состояния',
               existing_comment='Дата создания',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sync_states', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='последняя попытка синхронизации',
               existing_nullable=True)
    op.alter_column('user_sync_states', 'last_success_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='последний успешный синк',
               existing_nullable=True)
    op.alter_column('user_sync_states', 'last_error',
               existing_type=sa.TEXT(),
               comment='текст последней ошибки',
               existing_nullable=True)
    op.create_foreign_key(None, 'wb_realization_reports', 'api_tokens', ['token_id'], ['id'], ondelete='CASCADE')
    op.drop_column('wb_realization_reports', 'return_rub')
    op.add_column('wb_stocks', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.alter_column('wb_stocks', 'token_id',
               existing_type=sa.UUID(),
               existing_nullable=False)
    op.alter_column('wb_stocks', 'nm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wb_stocks', 'warehouse_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('wb_stocks', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wb_stocks', 'in_way_to_client',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wb_stocks', 'in_way_from_client',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_wb_stock_token_nm'), table_name='wb_stocks')
    op.drop_index(op.f('idx_wb_stock_user_nm'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_barcode'), table_name='wb_stocks')
    op.drop_constraint(op.f('uq_wb_stock_unique'), 'wb_stocks', type_='unique')
    op.create_index(op.f('ix_wb_stocks_warehouse_id'), 'wb_stocks', ['warehouse_id'], unique=False)
    op.create_unique_constraint('uq_wb_stock_ui', 'wb_stocks', ['token_id', 'nm_id', 'warehouse_id'])
    op.drop_column('wb_stocks', 'barcode')
    op.drop_column('wb_stocks', 'is_realization')
    op.drop_column('wb_stocks', 'tech_size')
    op.drop_column('wb_stocks', 'subject')
    op.drop_column('wb_stocks', 'supplier_article')
    op.drop_column('wb_stocks', 'is_supply')
    op.drop_column('wb_stocks', 'quantity_full')
    op.drop_column('wb_stocks', 'sc_code')
    op.drop_column('wb_stocks', 'brand')
    op.drop_column('wb_stocks', 'category')
    op.drop_column('wb_stocks', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_stocks', sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wb_stocks', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('wb_stocks', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('wb_stocks', sa.Column('sc_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('wb_stocks', sa.Column('quantity_full', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('wb_stocks', sa.Column('is_supply', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('wb_stocks', sa.Column('supplier_article', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('wb_stocks', sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('wb_stocks', sa.Column('tech_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('wb_stocks', sa.Column('is_realization', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('wb_stocks', sa.Column('barcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint('uq_wb_stock_ui', 'wb_stocks', type_='unique')
    op.drop_index(op.f('ix_wb_stocks_warehouse_id'), table_name='wb_stocks')
    op.create_unique_constraint(op.f('uq_wb_stock_unique'), 'wb_stocks', ['token_id', 'nm_id', 'warehouse_name', 'barcode'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_wb_stocks_barcode'), 'wb_stocks', ['barcode'], unique=False)
    op.create_index(op.f('idx_wb_stock_user_nm'), 'wb_stocks', ['user_id', 'nm_id'], unique=False)
    op.create_index(op.f('idx_wb_stock_token_nm'), 'wb_stocks', ['token_id', 'nm_id'], unique=False)
    op.alter_column('wb_stocks', 'in_way_from_client',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wb_stocks', 'in_way_to_client',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wb_stocks', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wb_stocks', 'warehouse_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('wb_stocks', 'nm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wb_stocks', 'token_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('wb_stocks', 'warehouse_id')
    op.add_column('wb_realization_reports', sa.Column('return_rub', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wb_realization_reports', type_='foreignkey')
    op.alter_column('user_sync_states', 'last_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='текст последней ошибки',
               existing_nullable=True)
    op.alter_column('user_sync_states', 'last_success_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='последний успешный синк',
               existing_nullable=True)
    op.alter_column('user_sync_states', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='последняя попытка синхронизации',
               existing_nullable=True)
    op.alter_column('user_sync_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата создания',
               existing_comment='когда создали запись состояния',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sync_states', 'entity',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='тип данных, которые ты синкаешь',
               existing_nullable=False)
    op.alter_column('user_sync_states', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='кому принадлежит состояние',
               existing_nullable=False)
    # ### end Alembic commands ###
