"""add propuct table for sync

Revision ID: 52b425d5e581
Revises: df00887f9039
Create Date: 2026-04-08 10:59:52.073973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b425d5e581'
down_revision: Union[str, Sequence[str], None] = 'df00887f9039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_product_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('nm_uuid', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_code', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('characteristics', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wb_product_nm_uuid', 'wb_product_cards', ['nm_uuid'], unique=False)
    op.create_index(op.f('ix_wb_product_cards_nm_id'), 'wb_product_cards', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_product_cards_subject_id'), 'wb_product_cards', ['subject_id'], unique=False)
    op.create_index(op.f('ix_wb_product_cards_subject_name'), 'wb_product_cards', ['subject_name'], unique=False)
    op.create_index(op.f('ix_wb_product_cards_user_id'), 'wb_product_cards', ['user_id'], unique=False)
    op.create_index(op.f('ix_wb_product_cards_vendor_code'), 'wb_product_cards', ['vendor_code'], unique=False)
    op.create_index('uq_wb_product_user_nmid', 'wb_product_cards', ['user_id', 'nm_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_wb_product_user_nmid', table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_vendor_code'), table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_user_id'), table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_subject_name'), table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_subject_id'), table_name='wb_product_cards')
    op.drop_index(op.f('ix_wb_product_cards_nm_id'), table_name='wb_product_cards')
    op.drop_index('idx_wb_product_nm_uuid', table_name='wb_product_cards')
    op.drop_table('wb_product_cards')
    # ### end Alembic commands ###
