"""create order reportr

Revision ID: 56e8bac332c8
Revises: b25d12d56ca8
Create Date: 2026-03-16 09:53:08.540202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e8bac332c8'
down_revision: Union[str, Sequence[str], None] = 'b25d12d56ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_realization_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rr_dt', sa.Date(), nullable=False),
    sa.Column('order_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('create_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('rrd_id', sa.Integer(), nullable=False),
    sa.Column('realizationreport_id', sa.Integer(), nullable=False),
    sa.Column('gi_id', sa.Integer(), nullable=True),
    sa.Column('srid', sa.String(length=200), nullable=True),
    sa.Column('order_uid', sa.String(length=200), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('shk_id', sa.Integer(), nullable=True),
    sa.Column('supplier_oper_name', sa.String(length=100), nullable=False),
    sa.Column('doc_type_name', sa.String(length=100), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('sa_name', sa.String(length=200), nullable=True),
    sa.Column('ts_name', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('kiz', sa.String(length=500), nullable=True),
    sa.Column('office_name', sa.String(length=200), nullable=True),
    sa.Column('retail_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('retail_price_withdisc_rub', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_amount', sa.Integer(), nullable=True),
    sa.Column('return_amount', sa.Integer(), nullable=True),
    sa.Column('ppvz_sales_commission', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('delivery_rub', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('return_rub', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('penalty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('additional_payment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('storage_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ppvz_for_pay', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ppvz_reward', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('acquiring_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sale_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ppvz_spp_prc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ppvz_kvw_prc_base', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ppvz_kvw_prc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ppvz_vw', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ppvz_vw_nds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wb_realization_user_nm_rrdt', 'wb_realization_reports', ['user_id', 'nm_id', 'rr_dt'], unique=False)
    op.create_index('idx_wb_realization_user_rrdt', 'wb_realization_reports', ['user_id', 'rr_dt'], unique=False)
    op.create_index(op.f('ix_wb_realization_reports_nm_id'), 'wb_realization_reports', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_realization_reports_realizationreport_id'), 'wb_realization_reports', ['realizationreport_id'], unique=False)
    op.create_index(op.f('ix_wb_realization_reports_rr_dt'), 'wb_realization_reports', ['rr_dt'], unique=False)
    op.create_index(op.f('ix_wb_realization_reports_rrd_id'), 'wb_realization_reports', ['rrd_id'], unique=True)
    op.create_index(op.f('ix_wb_realization_reports_srid'), 'wb_realization_reports', ['srid'], unique=False)
    op.create_index(op.f('ix_wb_realization_reports_supplier_oper_name'), 'wb_realization_reports', ['supplier_oper_name'], unique=False)
    op.create_index(op.f('ix_wb_realization_reports_user_id'), 'wb_realization_reports', ['user_id'], unique=False)
    op.create_index('uq_wb_realization_rrd_id', 'wb_realization_reports', ['rrd_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_wb_realization_rrd_id', table_name='wb_realization_reports')
    op.drop_index(op.f('ix_wb_realization_reports_user_id'), table_name='wb_realization_reports')
    op.drop_index(op.f('ix_wb_realization_reports_supplier_oper_name'), table_name='wb_realization_reports')
    op.drop_index(op.f('ix_wb_realization_reports_srid'), table_name='wb_realization_reports')
    op.drop_index(op.f('ix_wb_realization_reports_rrd_id'), table_name='wb_realization_reports')
    op.drop_index(op.f('ix_wb_realization_reports_rr_dt'), table_name='wb_realization_reports')
    op.drop_index(op.f('ix_wb_realization_reports_realizationreport_id'), table_name='wb_realization_reports')
    op.drop_index(op.f('ix_wb_realization_reports_nm_id'), table_name='wb_realization_reports')
    op.drop_index('idx_wb_realization_user_rrdt', table_name='wb_realization_reports')
    op.drop_index('idx_wb_realization_user_nm_rrdt', table_name='wb_realization_reports')
    op.drop_table('wb_realization_reports')
    # ### end Alembic commands ###
