"""init

Revision ID: 6465337d033f
Revises: 
Create Date: 2025-11-18 14:58:19.679962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6465337d033f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный ID пользователя'),
    sa.Column('email', sa.String(length=254), nullable=False, comment='Email для входа'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Номер телефона (для 2FA и уведомлений)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хэш пароля (bcrypt)'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='ФИО (для физлиц) / Название компании (для юрлиц)'),
    sa.Column('entity_type', sa.String(length=20), nullable=False, comment="'individual', 'self_employed', 'legal_entity'"),
    sa.Column('inn', sa.String(length=12), nullable=True, comment='ИНН (опционально для физлиц, обязательно для юрлиц)'),
    sa.Column('kpp', sa.String(length=9), nullable=True, comment='КПП (только для юрлиц, nullable)'),
    sa.Column('legal_address', sa.Text(), nullable=True, comment='Юридический адрес (юрлица)'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='Часовой пояс'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата регистрации'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли аккаунт'),
    sa.Column('is_staff', sa.Boolean(), nullable=False, comment='Является ли сотрудником системы'),
    sa.Column('staff_id', sa.String(length=50), nullable=True, comment='Внутренний ID сотрудника'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='Отдел/Департамент'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='Должность'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_index('idx_users_active_entity', 'users', ['is_active', 'entity_type'], unique=False)
    op.create_index('idx_users_auth', 'users', ['email', 'phone', 'is_active'], unique=False)
    op.create_index('idx_users_legal_info', 'users', ['entity_type', 'inn', 'kpp'], unique=False)
    op.create_index('idx_users_phone_email_unique', 'users', ['phone', 'email'], unique=True)
    op.create_index('idx_users_staff', 'users', ['is_staff', 'department'], unique=False)
    op.create_index('idx_users_staff_id', 'users', ['staff_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_entity_type'), 'users', ['entity_type'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_permissions', 'role_permissions', ['role', 'permission_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_roles_role', 'user_roles', ['role'], unique=False)
    op.create_index('idx_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_roles_user_id', table_name='user_roles')
    op.drop_index('idx_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_role_permissions', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_entity_type'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_staff_id', table_name='users')
    op.drop_index('idx_users_staff', table_name='users')
    op.drop_index('idx_users_phone_email_unique', table_name='users')
    op.drop_index('idx_users_legal_info', table_name='users')
    op.drop_index('idx_users_auth', table_name='users')
    op.drop_index('idx_users_active_entity', table_name='users')
    op.drop_table('users')
    op.drop_table('permissions')
    # ### end Alembic commands ###
