"""update limit table

Revision ID: 7b36ace515f2
Revises: 86a7fe77927e
Create Date: 2026-01-20 10:45:57.130671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b36ace515f2'
down_revision: Union[str, Sequence[str], None] = '86a7fe77927e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_limits', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff_limits', 'id')
    # ### end Alembic commands ###
