"""add subscription table

Revision ID: 86a7fe77927e
Revises: bd73fed66fd1
Create Date: 2026-01-12 15:46:25.672180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a7fe77927e'
down_revision: Union[str, Sequence[str], None] = 'bd73fed66fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор подписки'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Владелец подписки'),
    sa.Column('tariff_id', sa.UUID(), nullable=False, comment='Текущий тариф'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Статус: 'active', 'expired', 'cancelled', 'demo'"),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False, comment='Начало текущего оплаченного периода'),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False, comment='Конец текущего оплаченного периода'),
    sa.Column('yookassa_payment_id', sa.Text(), nullable=True, comment='ID платежа в ЮKassa (null для демо-подписок)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата оформления подписки'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Последнее обновление статуса или периода'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariff_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_tariff_id'), 'subscriptions', ['tariff_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tariff_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
