"""добавил поле дату создания

Revision ID: 8e3407b4c6d9
Revises: 2f92c5b859dc
Create Date: 2026-04-23 11:28:20.068538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3407b4c6d9'
down_revision: Union[str, Sequence[str], None] = '2f92c5b859dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sync_states', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sync_states', 'created_at')
    # ### end Alembic commands ###
