"""change user roles table

Revision ID: 9104a9446775
Revises: 7b36ace515f2
Create Date: 2026-01-21 15:37:12.655878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9104a9446775'
down_revision: Union[str, Sequence[str], None] = '7b36ace515f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('assigned_by', sa.UUID(), nullable=True))
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('uq_user_role', 'user_roles', ['user_id', 'role'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_role', table_name='user_roles')
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('user_roles', 'assigned_by')
    # ### end Alembic commands ###
