"""создаем талбицу с рекламной статистикой

Revision ID: 93fe0c5c3f68
Revises: d9902a74f324
Create Date: 2026-05-06 10:26:37.118195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fe0c5c3f68'
down_revision: Union[str, Sequence[str], None] = 'd9902a74f324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_advertising_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_type', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('added_to_cart', sa.Integer(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('cr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('shks', sa.Integer(), nullable=False),
    sa.Column('orders_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('avg_position', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wb_adv_campaign_date', 'wb_advertising_stats', ['campaign_id', 'date'], unique=False)
    op.create_index('idx_wb_adv_unique', 'wb_advertising_stats', ['user_id', 'campaign_id', 'nm_id', 'date', 'platform_type'], unique=True)
    op.create_index('idx_wb_adv_user_date', 'wb_advertising_stats', ['user_id', 'date'], unique=False)
    op.create_index('idx_wb_adv_user_nm_date', 'wb_advertising_stats', ['user_id', 'nm_id', 'date'], unique=False)
    op.create_index(op.f('ix_wb_advertising_stats_campaign_id'), 'wb_advertising_stats', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_wb_advertising_stats_date'), 'wb_advertising_stats', ['date'], unique=False)
    op.create_index(op.f('ix_wb_advertising_stats_nm_id'), 'wb_advertising_stats', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_advertising_stats_token_id'), 'wb_advertising_stats', ['token_id'], unique=False)
    op.create_index(op.f('ix_wb_advertising_stats_user_id'), 'wb_advertising_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_advertising_stats_user_id'), table_name='wb_advertising_stats')
    op.drop_index(op.f('ix_wb_advertising_stats_token_id'), table_name='wb_advertising_stats')
    op.drop_index(op.f('ix_wb_advertising_stats_nm_id'), table_name='wb_advertising_stats')
    op.drop_index(op.f('ix_wb_advertising_stats_date'), table_name='wb_advertising_stats')
    op.drop_index(op.f('ix_wb_advertising_stats_campaign_id'), table_name='wb_advertising_stats')
    op.drop_index('idx_wb_adv_user_nm_date', table_name='wb_advertising_stats')
    op.drop_index('idx_wb_adv_user_date', table_name='wb_advertising_stats')
    op.drop_index('idx_wb_adv_unique', table_name='wb_advertising_stats')
    op.drop_index('idx_wb_adv_campaign_date', table_name='wb_advertising_stats')
    op.drop_table('wb_advertising_stats')
    # ### end Alembic commands ###
