"""чистим модель репорт

Revision ID: 997b0c34c0b1
Revises: 35a99a7be8fa
Create Date: 2026-04-28 13:37:49.590736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997b0c34c0b1'
down_revision: Union[str, Sequence[str], None] = '35a99a7be8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_realization_reports_realizationreport_id'), table_name='wb_realization_reports')
    op.drop_index(op.f('uq_wb_realization_rrd_id'), table_name='wb_realization_reports')
    op.drop_column('wb_realization_reports', 'brand_name')
    op.drop_column('wb_realization_reports', 'commission_percent')
    op.drop_column('wb_realization_reports', 'ppvz_kvw_prc_base')
    op.drop_column('wb_realization_reports', 'ppvz_kvw_prc')
    op.drop_column('wb_realization_reports', 'subject_name')
    op.drop_column('wb_realization_reports', 'barcode')
    op.drop_column('wb_realization_reports', 'additional_payment')
    op.drop_column('wb_realization_reports', 'acquiring_fee')
    op.drop_column('wb_realization_reports', 'ppvz_vw_nds')
    op.drop_column('wb_realization_reports', 'sale_percent')
    op.drop_column('wb_realization_reports', 'sa_name')
    op.drop_column('wb_realization_reports', 'delivery_amount')
    op.drop_column('wb_realization_reports', 'return_amount')
    op.drop_column('wb_realization_reports', 'shk_id')
    op.drop_column('wb_realization_reports', 'ppvz_reward')
    op.drop_column('wb_realization_reports', 'doc_type_name')
    op.drop_column('wb_realization_reports', 'ppvz_spp_prc')
    op.drop_column('wb_realization_reports', 'assembly_id')
    op.drop_column('wb_realization_reports', 'gi_id')
    op.drop_column('wb_realization_reports', 'storage_fee')
    op.drop_column('wb_realization_reports', 'realizationreport_id')
    op.drop_column('wb_realization_reports', 'retail_price')
    op.drop_column('wb_realization_reports', 'ppvz_vw')
    op.drop_column('wb_realization_reports', 'kiz')
    op.drop_column('wb_realization_reports', 'penalty')
    op.drop_column('wb_realization_reports', 'ts_name')
    op.drop_column('wb_realization_reports', 'order_uid')
    op.drop_column('wb_realization_reports', 'retail_price_withdisc_rub')
    op.alter_column(
        'wb_stocks',
        'token_id',
        existing_type=sa.String(length=36),
        type_=sa.UUID(),
        postgresql_using="token_id::uuid"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wb_stocks', 'token_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('wb_realization_reports', sa.Column('retail_price_withdisc_rub', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('order_uid', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ts_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('penalty', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('wb_realization_reports', sa.Column('kiz', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_vw', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('retail_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('realizationreport_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('wb_realization_reports', sa.Column('storage_fee', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('wb_realization_reports', sa.Column('gi_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('assembly_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_spp_prc', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('doc_type_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_reward', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('shk_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('return_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('delivery_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('sa_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('sale_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_vw_nds', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('acquiring_fee', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('additional_payment', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('wb_realization_reports', sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('subject_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_kvw_prc', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_kvw_prc_base', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('commission_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('wb_realization_reports', sa.Column('brand_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_wb_realization_rrd_id'), 'wb_realization_reports', ['rrd_id'], unique=True)
    op.create_index(op.f('ix_wb_realization_reports_realizationreport_id'), 'wb_realization_reports', ['realizationreport_id'], unique=False)
    # ### end Alembic commands ###
