"""пересоздаем таблицу репорт

Revision ID: 9bf93304ee38
Revises: 12de4d08eb1d
Create Date: 2026-04-29 11:36:04.623730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf93304ee38'
down_revision: Union[str, Sequence[str], None] = '12de4d08eb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_realization_reports', sa.Column('gi_id', sa.Integer(), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('shk_id', sa.Integer(), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('realization_report_id', sa.Integer(), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('doc_type_name', sa.String(length=100), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('subject_name', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('brand_name', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('sa_name', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ts_name', sa.String(length=100), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('barcode', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('gi_box_type_name', sa.String(length=100), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_office_id', sa.Integer(), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_office_name', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('retail_price', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('retail_price_with_disc_rub', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('sale_percent', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('commission_percent', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('product_discount_for_report', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_spp_prc', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_kvw_prc_base', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_kvw_prc', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('sup_rating_prc_up', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('is_kgvp_v2', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_reward', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_vw', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_vw_nds', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('return_rub', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('delivery_amount', sa.Integer(), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('return_amount', sa.Integer(), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('rebill_logistic_cost', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('rebill_logistic_org', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('storage_fee', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('acceptance', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('penalty', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('additional_payment', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('deduction', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('acquiring_fee', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('acquiring_bank', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('supplier_promo', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('order_uid', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('kiz', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('declaration_number', sa.String(length=200), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_supplier_id', sa.Integer(), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_supplier_name', sa.String(length=300), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('ppvz_inn', sa.String(length=20), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('currency_name', sa.String(length=50), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('report_type', sa.Integer(), nullable=True))
    op.add_column('wb_realization_reports', sa.Column('trbx_id', sa.String(length=50), nullable=True))
    op.create_index('idx_wb_realization_barcode', 'wb_realization_reports', ['barcode'], unique=False)
    op.create_index('idx_wb_realization_brand', 'wb_realization_reports', ['brand_name'], unique=False)
    op.create_index(op.f('ix_wb_realization_reports_barcode'), 'wb_realization_reports', ['barcode'], unique=False)
    op.create_index(op.f('ix_wb_realization_reports_brand_name'), 'wb_realization_reports', ['brand_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_realization_reports_brand_name'), table_name='wb_realization_reports')
    op.drop_index(op.f('ix_wb_realization_reports_barcode'), table_name='wb_realization_reports')
    op.drop_index('idx_wb_realization_brand', table_name='wb_realization_reports')
    op.drop_index('idx_wb_realization_barcode', table_name='wb_realization_reports')
    op.drop_column('wb_realization_reports', 'trbx_id')
    op.drop_column('wb_realization_reports', 'report_type')
    op.drop_column('wb_realization_reports', 'currency_name')
    op.drop_column('wb_realization_reports', 'ppvz_inn')
    op.drop_column('wb_realization_reports', 'ppvz_supplier_name')
    op.drop_column('wb_realization_reports', 'ppvz_supplier_id')
    op.drop_column('wb_realization_reports', 'declaration_number')
    op.drop_column('wb_realization_reports', 'kiz')
    op.drop_column('wb_realization_reports', 'order_uid')
    op.drop_column('wb_realization_reports', 'supplier_promo')
    op.drop_column('wb_realization_reports', 'acquiring_bank')
    op.drop_column('wb_realization_reports', 'acquiring_fee')
    op.drop_column('wb_realization_reports', 'deduction')
    op.drop_column('wb_realization_reports', 'additional_payment')
    op.drop_column('wb_realization_reports', 'penalty')
    op.drop_column('wb_realization_reports', 'acceptance')
    op.drop_column('wb_realization_reports', 'storage_fee')
    op.drop_column('wb_realization_reports', 'rebill_logistic_org')
    op.drop_column('wb_realization_reports', 'rebill_logistic_cost')
    op.drop_column('wb_realization_reports', 'return_amount')
    op.drop_column('wb_realization_reports', 'delivery_amount')
    op.drop_column('wb_realization_reports', 'return_rub')
    op.drop_column('wb_realization_reports', 'ppvz_vw_nds')
    op.drop_column('wb_realization_reports', 'ppvz_vw')
    op.drop_column('wb_realization_reports', 'ppvz_reward')
    op.drop_column('wb_realization_reports', 'is_kgvp_v2')
    op.drop_column('wb_realization_reports', 'sup_rating_prc_up')
    op.drop_column('wb_realization_reports', 'ppvz_kvw_prc')
    op.drop_column('wb_realization_reports', 'ppvz_kvw_prc_base')
    op.drop_column('wb_realization_reports', 'ppvz_spp_prc')
    op.drop_column('wb_realization_reports', 'product_discount_for_report')
    op.drop_column('wb_realization_reports', 'commission_percent')
    op.drop_column('wb_realization_reports', 'sale_percent')
    op.drop_column('wb_realization_reports', 'retail_price_with_disc_rub')
    op.drop_column('wb_realization_reports', 'retail_price')
    op.drop_column('wb_realization_reports', 'ppvz_office_name')
    op.drop_column('wb_realization_reports', 'ppvz_office_id')
    op.drop_column('wb_realization_reports', 'gi_box_type_name')
    op.drop_column('wb_realization_reports', 'title')
    op.drop_column('wb_realization_reports', 'barcode')
    op.drop_column('wb_realization_reports', 'ts_name')
    op.drop_column('wb_realization_reports', 'sa_name')
    op.drop_column('wb_realization_reports', 'brand_name')
    op.drop_column('wb_realization_reports', 'subject_name')
    op.drop_column('wb_realization_reports', 'doc_type_name')
    op.drop_column('wb_realization_reports', 'realization_report_id')
    op.drop_column('wb_realization_reports', 'shk_id')
    op.drop_column('wb_realization_reports', 'gi_id')
    # ### end Alembic commands ###
