"""изменение таблицы задач

Revision ID: adbdd24d437b
Revises: 8e3407b4c6d9
Create Date: 2026-04-23 14:21:51.942551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adbdd24d437b'
down_revision: Union[str, Sequence[str], None] = '8e3407b4c6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_jobs', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_sync_jobs_token_id'), table_name='sync_jobs')
    op.create_index(op.f('ix_sync_jobs_is_active'), 'sync_jobs', ['is_active'], unique=False)
    op.create_unique_constraint('uq_job_unique_pending', 'sync_jobs', ['user_id', 'entity', 'status'])
    op.drop_constraint(op.f('sync_jobs_token_id_fkey'), 'sync_jobs', type_='foreignkey')
    op.drop_column('sync_jobs', 'token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_jobs', sa.Column('token_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sync_jobs_token_id_fkey'), 'sync_jobs', 'api_tokens', ['token_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_job_unique_pending', 'sync_jobs', type_='unique')
    op.drop_index(op.f('ix_sync_jobs_is_active'), table_name='sync_jobs')
    op.create_index(op.f('ix_sync_jobs_token_id'), 'sync_jobs', ['token_id'], unique=False)
    op.drop_column('sync_jobs', 'is_active')
    # ### end Alembic commands ###
