"""update apitokens

Revision ID: b25d12d56ca8
Revises: 358272a0d6c2
Create Date: 2026-03-13 13:40:58.046461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25d12d56ca8'
down_revision: Union[str, Sequence[str], None] = '358272a0d6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('api_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    op.alter_column('api_tokens', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tokens', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('api_tokens', 'is_revoked')
    op.drop_column('api_tokens', 'is_active')
    # ### end Alembic commands ###
