"""изменение уникального ключа

Revision ID: b632c3f97fb6
Revises: adbdd24d437b
Create Date: 2026-04-23 16:39:02.273655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b632c3f97fb6'
down_revision: Union[str, Sequence[str], None] = 'adbdd24d437b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_unique_pending', 'sync_jobs', type_='unique')
    # ✅ создать partial index
    op.create_index(
        'uq_job_active',
        'sync_jobs',
        ['user_id', 'entity'],
        unique=True,
        postgresql_where=sa.text('is_active = true')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_job_active', table_name='sync_jobs')
    op.create_unique_constraint(
        'uq_job_unique_pending',
        'sync_jobs',
        ['user_id', 'entity', 'status']
    )
    # ### end Alembic commands ###
