"""add tariff_limits table

Revision ID: bd73fed66fd1
Revises: c6e37ecc6376
Create Date: 2026-01-12 15:40:59.379636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd73fed66fd1'
down_revision: Union[str, Sequence[str], None] = 'c6e37ecc6376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_limits',
    sa.Column('tariff_id', sa.UUID(), nullable=False, comment='Ссылка на тариф'),
    sa.Column('limit_type', sa.String(length=50), nullable=False, comment="Тип лимита: 'wb_accounts', 'nm_ids', 'sync_frequency_hours', 'ai_queries_per_month', 'retention_days'"),
    sa.Column('limit_value', sa.Integer(), nullable=False, comment='Числовое значение лимита'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariff_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tariff_id', 'limit_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariff_limits')
    # ### end Alembic commands ###
