"""add tariff_plans table

Revision ID: c6e37ecc6376
Revises: 6465337d033f
Create Date: 2026-01-12 15:31:47.962410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e37ecc6376'
down_revision: Union[str, Sequence[str], None] = '6465337d033f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_plans',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор'),
    sa.Column('code', sa.String(length=50), nullable=False, comment="Код тарифа: 'demo', 'starter', 'pro', 'enterprise'"),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Отображаемое название: 'Демо', 'Старт (для ИП)', 'Про', 'Бизнес'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание для лендинга: "7 дней бесплатно, без карты"'),
    sa.Column('price_rub', sa.Numeric(precision=10, scale=2), nullable=False, comment='Цена в рублях за месяц (0.00 для демо)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли тариф (можно скрыть без удаления)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда создан'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Последнее изменение цены/лимитов'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariff_plans')
    # ### end Alembic commands ###
