"""добавляем таблицу оплаты

Revision ID: d3cce3802954
Revises: 133e43685280
Create Date: 2026-04-20 15:29:08.385920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cce3802954'
down_revision: Union[str, Sequence[str], None] = '133e43685280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    bind = op.get_bind()

    # --- ENUM для subscription ---
    subscription_status_enum = postgresql.ENUM(
        'demo', 'active', 'expired', 'cancelled',
        name='subscription_status',
        create_type=False
    )
    subscription_status_enum.create(bind, checkfirst=True)

    # --- ENUM для payment ---
    payment_status_enum = postgresql.ENUM(
        'pending', 'succeeded', 'failed', 'cancelled',
        name='payment_status',
        create_type=False
    )
    payment_provider_enum = postgresql.ENUM(
        'fake', 'yookassa',
        name='payment_provider',
        create_type=False
    )

    payment_status_enum.create(bind, checkfirst=True)
    payment_provider_enum.create(bind, checkfirst=True)

    # --- таблица payments ---
    op.create_table(
        'payments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tariff_id', sa.UUID(), nullable=False),
        sa.Column('amount', sa.Numeric(10, 2), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('status', payment_status_enum, nullable=False),
        sa.Column('provider', payment_provider_enum, nullable=False),
        sa.Column('external_payment_id', sa.Text(), nullable=True),
        sa.Column('provider_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['tariff_id'], ['tariff_plans.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index('ix_payments_user_id', 'payments', ['user_id'])

    # --- меняем subscriptions.status ---
    op.alter_column(
        'subscriptions',
        'status',
        existing_type=sa.VARCHAR(length=20),
        type_=subscription_status_enum,
        existing_nullable=False,
        postgresql_using="status::subscription_status"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    # возвращаем строку
    op.alter_column(
        'subscriptions',
        'status',
        existing_type=sa.Enum(name='subscription_status'),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False
    )

    op.drop_index('ix_payments_user_id', table_name='payments')
    op.drop_table('payments')

    # удаляем ENUM
    postgresql.ENUM(name='payment_provider').drop(bind, checkfirst=True)
    postgresql.ENUM(name='payment_status').drop(bind, checkfirst=True)
    postgresql.ENUM(name='subscription_status').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
