"""создание таблицы себестоимости

Revision ID: d9902a74f324
Revises: 9bf93304ee38
Create Date: 2026-04-29 14:55:15.220038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9902a74f324'
down_revision: Union[str, Sequence[str], None] = '9bf93304ee38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_cost_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('seller_sku', sa.String(length=200), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'nm_id', name='uq_user_nm_cost_price')
    )
    op.create_index('idx_product_cost_seller_sku', 'product_cost_prices', ['seller_sku'], unique=False)
    op.create_index('idx_product_cost_user_nm', 'product_cost_prices', ['user_id', 'nm_id'], unique=False)
    op.create_index(op.f('ix_product_cost_prices_nm_id'), 'product_cost_prices', ['nm_id'], unique=False)
    op.create_index(op.f('ix_product_cost_prices_seller_sku'), 'product_cost_prices', ['seller_sku'], unique=False)
    op.create_index(op.f('ix_product_cost_prices_user_id'), 'product_cost_prices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_cost_prices_user_id'), table_name='product_cost_prices')
    op.drop_index(op.f('ix_product_cost_prices_seller_sku'), table_name='product_cost_prices')
    op.drop_index(op.f('ix_product_cost_prices_nm_id'), table_name='product_cost_prices')
    op.drop_index('idx_product_cost_user_nm', table_name='product_cost_prices')
    op.drop_index('idx_product_cost_seller_sku', table_name='product_cost_prices')
    op.drop_table('product_cost_prices')
    # ### end Alembic commands ###
