"""новые таблицы

Revision ID: db78d6fee9e1
Revises: d3cce3802954
Create Date: 2026-04-22 10:14:40.371536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db78d6fee9e1'
down_revision: Union[str, Sequence[str], None] = 'd3cce3802954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_status'), 'sync_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_sync_jobs_token_id'), 'sync_jobs', ['token_id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_user_id'), 'sync_jobs', ['user_id'], unique=False)
    op.create_table('user_sync_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token_id', 'entity', name='uq_sync_state')
    )
    op.create_index(op.f('ix_user_sync_states_entity'), 'user_sync_states', ['entity'], unique=False)
    op.create_index(op.f('ix_user_sync_states_token_id'), 'user_sync_states', ['token_id'], unique=False)
    op.create_index(op.f('ix_user_sync_states_user_id'), 'user_sync_states', ['user_id'], unique=False)
    op.create_table('wb_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('supplier_article', sa.String(length=100), nullable=True),
    sa.Column('warehouse_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_full', sa.Integer(), nullable=False),
    sa.Column('in_way_to_client', sa.Integer(), nullable=False),
    sa.Column('in_way_from_client', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('tech_size', sa.String(length=50), nullable=True),
    sa.Column('is_supply', sa.Boolean(), nullable=True),
    sa.Column('is_realization', sa.Boolean(), nullable=True),
    sa.Column('sc_code', sa.String(length=50), nullable=True),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'nm_id', 'warehouse_name', 'barcode', name='uq_wb_stock_unique')
    )
    op.create_index('idx_wb_stock_token_nm', 'wb_stocks', ['token_id', 'nm_id'], unique=False)
    op.create_index('idx_wb_stock_user_nm', 'wb_stocks', ['user_id', 'nm_id'], unique=False)
    op.create_index(op.f('ix_wb_stocks_barcode'), 'wb_stocks', ['barcode'], unique=False)
    op.create_index(op.f('ix_wb_stocks_last_change_date'), 'wb_stocks', ['last_change_date'], unique=False)
    op.create_index(op.f('ix_wb_stocks_nm_id'), 'wb_stocks', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_stocks_token_id'), 'wb_stocks', ['token_id'], unique=False)
    op.create_index(op.f('ix_wb_stocks_user_id'), 'wb_stocks', ['user_id'], unique=False)
    op.create_index(op.f('ix_wb_stocks_warehouse_name'), 'wb_stocks', ['warehouse_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_stocks_warehouse_name'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_user_id'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_token_id'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_nm_id'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_last_change_date'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_barcode'), table_name='wb_stocks')
    op.drop_index('idx_wb_stock_user_nm', table_name='wb_stocks')
    op.drop_index('idx_wb_stock_token_nm', table_name='wb_stocks')
    op.drop_table('wb_stocks')
    op.drop_index(op.f('ix_user_sync_states_user_id'), table_name='user_sync_states')
    op.drop_index(op.f('ix_user_sync_states_token_id'), table_name='user_sync_states')
    op.drop_index(op.f('ix_user_sync_states_entity'), table_name='user_sync_states')
    op.drop_table('user_sync_states')
    op.drop_index(op.f('ix_sync_jobs_user_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_token_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_status'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    # ### end Alembic commands ###
