"""update_user_table

Revision ID: fa0fae3a0187
Revises: 56e8bac332c8
Create Date: 2026-03-30 13:39:20.505174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0fae3a0187'
down_revision: Union[str, Sequence[str], None] = '56e8bac332c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tax_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tax_rate')
    # ### end Alembic commands ###
