[Service]
ExecStart=
ExecStart=/home/projects/wb/backend/venv/bin/python -m celery -A celery_app:celery_app beat --loglevel=info
Restart=always
RestartSec=3
Environment="PATH=/home/projects/wb/backend/venv/bin:/usr/bin:/usr/local/bin"
